import {
  op_create_window,
  op_request_quit,
  op_request_redraw,
  op_get_root_node_id,
  op_create_element,
  op_create_text_node,
  /** begin image */
  op_set_encoded_image_data,
  op_apply_cached_image,
  op_clear_image_data,
  /** end image */
  op_append_child,
  op_insert_before,
  op_remove_child,
  op_set_text,
  op_reset_dom,
  op_set_str_attribute,
  op_set_number_attribute,
  op_set_bool_attribute,
  op_clear_attribute,
  op_get_attribute,
  op_focus_input,
  op_set_rem_base,
  op_get_window_width,
  op_get_window_height,
  op_get_window_title,
  op_get_ancestor_path,
  op_read_clipboard_text,
  op_write_clipboard_text,
} from 'ext:core/ops';

Object.defineProperty(globalThis, '__uzumaki_ops_dont_touch_this__', {
  value: Object.freeze({
    createWindow: op_create_window,
    requestClose: op_request_quit,
    requestRedraw: op_request_redraw,
    getRootNodeId: op_get_root_node_id,
    createElement: op_create_element,
    createTextNode: op_create_text_node,
    setEncodedImageData: op_set_encoded_image_data,
    applyCachedImage: op_apply_cached_image,
    clearImageData: op_clear_image_data,
    appendChild: op_append_child,
    insertBefore: op_insert_before,
    removeChild: op_remove_child,
    setText: op_set_text,
    resetDom: op_reset_dom,
    setStrAttribute: op_set_str_attribute,
    setNumberAttribute: op_set_number_attribute,
    setBoolAttribute: op_set_bool_attribute,
    clearAttribute: op_clear_attribute,
    getAttribute: op_get_attribute,
    focusInput: op_focus_input,
    setRemBase: op_set_rem_base,
    getWindowWidth: op_get_window_width,
    getWindowHeight: op_get_window_height,
    getWindowTitle: op_get_window_title,
    getAncestorPath: op_get_ancestor_path,
    readClipboardText: op_read_clipboard_text,
    writeClipboardText: op_write_clipboard_text,
  }),
  writable: false,
  configurable: false,
});
