import {
  op_create_window,
  op_request_quit,
  op_request_redraw,
  op_get_root_node_id,
  op_create_element,
  op_create_text_node,
  op_append_child,
  op_insert_before,
  op_remove_child,
  op_set_text,
  op_reset_dom,
  op_set_length_prop,
  op_set_color_prop,
  op_set_f32_prop,
  op_set_enum_prop,
  op_set_string_prop,
  op_set_input_value,
  op_get_input_value,
  op_set_input_placeholder,
  op_set_input_disabled,
  op_set_input_max_length,
  op_set_input_multiline,
  op_set_input_secure,
  op_set_checkbox_checked,
  op_focus_input,
  op_set_rem_base,
  op_get_window_width,
  op_get_window_height,
  op_get_window_title,
  op_get_ancestor_path,
  op_read_clipboard_text,
  op_write_clipboard_text,
} from 'ext:core/ops';

Object.defineProperty(globalThis, '__uzumaki_ops_dont_touch_this__', {
  value: Object.freeze({
    createWindow: op_create_window,
    requestClose: op_request_quit,
    requestRedraw: op_request_redraw,
    getRootNodeId: op_get_root_node_id,
    createElement: op_create_element,
    createTextNode: op_create_text_node,
    appendChild: op_append_child,
    insertBefore: op_insert_before,
    removeChild: op_remove_child,
    setText: op_set_text,
    resetDom: op_reset_dom,
    setLengthProp: op_set_length_prop,
    setColorProp: op_set_color_prop,
    setF32Prop: op_set_f32_prop,
    setEnumProp: op_set_enum_prop,
    setStringProp: op_set_string_prop,
    setInputValue: op_set_input_value,
    getInputValue: op_get_input_value,
    setInputPlaceholder: op_set_input_placeholder,
    setInputDisabled: op_set_input_disabled,
    setInputMaxLength: op_set_input_max_length,
    setInputMultiline: op_set_input_multiline,
    setInputSecure: op_set_input_secure,
    setCheckboxChecked: op_set_checkbox_checked,
    focusInput: op_focus_input,
    setRemBase: op_set_rem_base,
    getWindowWidth: op_get_window_width,
    getWindowHeight: op_get_window_height,
    getWindowTitle: op_get_window_title,
    getAncestorPath: op_get_ancestor_path,
    readClipboardText: op_read_clipboard_text,
    writeClipboardText: op_write_clipboard_text,
  }),
  writable: false,
  configurable: false,
});
