use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    let o = std::path::PathBuf::from(std::env::var_os("OUT_DIR").unwrap());
    generate_prop_key_bindings(&o);
}

const PROP_KEYS: &[(&str, u32)] = &[
    ("W", 0),
    ("H", 1),
    ("P", 2),
    ("Px", 3),
    ("Py", 4),
    ("Pt", 5),
    ("Pb", 6),
    ("Pl", 7),
    ("Pr", 8),
    ("M", 9),
    ("Mx", 10),
    ("My", 11),
    ("Mt", 12),
    ("Mb", 13),
    ("Ml", 14),
    ("Mr", 15),
    ("Flex", 16),
    ("FlexDir", 17),
    ("FlexGrow", 18),
    ("FlexShrink", 19),
    ("Items", 20),
    ("Justify", 21),
    ("Gap", 22),
    ("Bg", 23),
    ("Color", 24),
    ("FontSize", 25),
    ("FontWeight", 26),
    ("Rounded", 27),
    ("RoundedTL", 28),
    ("RoundedTR", 29),
    ("RoundedBR", 30),
    ("RoundedBL", 31),
    ("Border", 32),
    ("BorderTop", 33),
    ("BorderRight", 34),
    ("BorderBottom", 35),
    ("BorderLeft", 36),
    ("BorderColor", 37),
    ("Opacity", 38),
    ("Display", 39),
    ("Cursor", 40),
    ("Interactive", 41),
    ("Visibility", 42),
    ("HoverBg", 43),
    ("HoverColor", 44),
    ("HoverOpacity", 45),
    ("HoverBorderColor", 46),
    ("ActiveBg", 47),
    ("ActiveColor", 48),
    ("ActiveOpacity", 49),
    ("ActiveBorderColor", 50),
    ("Scrollable", 51),
    ("MinW", 52),
    ("MinH", 53),
    ("TextSelect", 54),
];

fn generate_prop_key_bindings(out_dir: &Path) {
    let rust_path = out_dir.join("prop_keys.rs");
    write_if_changed(&rust_path, &render_rust_prop_keys());

    let js_path = Path::new("js").join("generated").join("prop_keys.ts");
    if let Some(parent) = js_path.parent() {
        fs::create_dir_all(parent).expect("failed to create js/generated directory");
    }
    write_if_changed(&js_path, &render_ts_prop_keys());
}

fn render_rust_prop_keys() -> String {
    let mut out = String::from(
        "// This file is @generated by crates/uzumaki/build.rs. Do not edit by hand.\n\
#[derive(Copy, Clone, Debug, Eq, PartialEq)]\n\
#[repr(u32)]\n\
pub enum PropKey {\n",
    );

    for (name, value) in PROP_KEYS {
        out.push_str(&format!("    {name} = {value},\n"));
    }

    out.push_str(
        "}\n\n\
impl core::convert::TryFrom<u32> for PropKey {\n\
    type Error = ();\n\n\
    fn try_from(value: u32) -> Result<Self, Self::Error> {\n\
        match value {\n",
    );

    for (name, value) in PROP_KEYS {
        out.push_str(&format!("            {value} => Ok(Self::{name}),\n"));
    }

    out.push_str(
        "            _ => Err(()),\n\
        }\n\
    }\n\
}\n",
    );

    out
}

fn render_ts_prop_keys() -> String {
    let mut out = String::from(
        "// This file is @generated by crates/uzumaki/build.rs. Do not edit by hand.\n\
export const enum PropKey {\n",
    );

    for (name, value) in PROP_KEYS {
        out.push_str(&format!("  {name} = {value},\n"));
    }

    out.push_str("}\n");
    out
}

fn write_if_changed(path: &Path, contents: &str) {
    let current = fs::read_to_string(path).ok();
    if current.as_deref() == Some(contents) {
        return;
    }
    fs::write(path, contents).unwrap_or_else(|err| {
        panic!("failed to write {}: {err}", path.display());
    });
}
